pipeline{
    agent any
    parameters {
        booleanParam(defaultValue:false, description: "enableservice?",name:"myBoolean")

    }
    stages{
        stage("Enable Service"){
            steps{
                echo "boolean param is set to ${params.myBoolean}"

            }
        }
    }
}