pipeline {
    agent any
   
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean install'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
            }
        }
        stage("ifstatements") {
            steps {
                script{
                    if(env.BRANCH_NAME=='master'){
                        echo "hello from master"
                    }
                }
            }
        }
    }
}
